version: '3.8'

networks:
  # Specify the network for bridging
  app-network:
    driver: bridge
services:
  netStateFE:
    build: ./
    # command: yarn run dev
    # environment:
    #   BACKEND_API: 'http://ec2-18-177-135-205.ap-northeast-1.compute.amazonaws.com:3002/'
    volumes:
      - './docker.nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - '80:80'
    restart: always
    networks:
      - app-network
